voyager_tls_broker_secret_name: "{{ vars | json_query('broker.tls_secret') | default(None, true) }}"

voyager_broker_ingress_config:
  type: "{{ vars | json_query('broker.type') | default('LoadBalancer', true) }}"
  load_balancer_ip: "{{ vars | json_query('broker.load_balancer_ip') | default(None, true) }}"
  replicas: "{{ vars | json_query('broker.replicas') | default(1, true) }}"
  node_selector: "{{ vars | json_query('broker.node_selector') | default(None, true) }}"
  max_connections: "{{ vars | json_query('broker.max_connections') | default(10000, true) }}"
