---
- name: Setting play-specific variables
  hosts: localhost
  remote_user: root
  connection: local
  tasks:
    - set_fact:
        astarte_resource_type: "AstarteVoyagerIngress"

- name: Gather facts from existing Astarte Operator object
  hosts: localhost
  remote_user: root
  connection: local
  tags:
    - operator
  roles:
    - name: astarte-k8s-facts
      when:
        - vars | json_query('meta.name')

- name: Deploy Voyager Broker Ingress
  hosts: localhost
  remote_user: root
  connection: local
  tags:
    - voyager
  roles:
    - name: voyager-broker-ingress
      when:
        - deploy_voyager_broker_ingress

- name: Deploy Voyager API Ingress
  hosts: localhost
  remote_user: root
  connection: local
  tags:
    - voyager
  roles:
    - name: voyager-api-ingress
      when:
        - deploy_voyager_api_ingress

- name: Obtain Voyager Let's Encrypt Certificate
  hosts: localhost
  remote_user: root
  connection: local
  tags:
    - voyager
    - letsencrypt
  roles:
    - name: voyager-certificate-letsencrypt
      when:
        - voyager_use_letsencrypt
        - deploy_voyager_broker_ingress or deploy_voyager_api_ingress
