apiVersion: api.astarte-platform.org/v1alpha1
kind: AstarteVoyagerIngress
metadata:
  name: example-minimal
  namespace: astarte
spec:
  ### Astarte Voyager Ingress CRD
  astarte: astarte
  api:
    deploy: true
    exposeHousekeeping: true
  dashboard:
    ssl: true
    host: "dashboard.astarte-example.com" # When not specified, dashboard will be deployed in /dashboard in the API host.
  broker:
    deploy: true
  letsencrypt:
    use: true
    acmeEmail: info@myowndomain.com
    challengeProvider:
      dns:
        provider: digitalocean
        credentialSecretName: voyager-digitalocean
