apiVersion: api.astarte-platform.org/v1alpha1
kind: AstarteVoyagerIngress
metadata:
  name: example
  namespace: astarte
spec:
  ### Astarte Voyager Ingress CRD
  imagePullPolicy: IfNotPresent
  astarte: example
  api:
    deploy: true
    cors: false
    replicas: 1
    type: LoadBalancer
    loadBalancerIp: "203.0.113.1"
    nodeSelector: "mynodeselector"
    exposeHousekeeping: true
    tlsSecret: my-custom-broker-ssl-certificate
    serveMetrics: true
    serveMetricsToSubnet: '198.51.100.0/24'
    annotationsService:
      service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
  dashboard:
    ssl: true
    host: "dashboard.astarte-example.com" # When not specified, dashboard will be deployed in /dashboard in the API host.
  broker:
    deploy: true
    replicas: 1
    type: LoadBalancer
    loadBalancerIp: "203.0.113.2"
    nodeSelector: "mynodeselector"
    maxConnections: 10000
    tlsSecret: my-custom-api-ssl-certificate
    annotationsService:
      service.beta.kubernetes.io/aws-load-balancer-internal": "0.0.0.0/0"
  letsencrypt:
    use: true
    staging: false
    acmeEmail: info@example.com
    domains:
      - broker.mydomain.com
      - api.mydomain.com
      - dashboard.mydomain.com
    challengeProvider:
      dns:
        provider: digitalocean
        credentialSecretName: voyager-digitalocean
