apiVersion: apps/v1
kind: Deployment
metadata:
  name: astarte-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: astarte-operator
  template:
    metadata:
      labels:
        name: astarte-operator
    spec:
      serviceAccountName: astarte-operator
      containers:
        - name: astarte-operator
          # Replace this with the built image name
          image: astarte/astarte-kubernetes-operator:0.11.0-beta.1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "astarte-operator"
