apiVersion: v2
name: astarte-operator
description: The Astarte Kubernetes Operator Helm Chart.
type: application

version: "24.5.0-rc.0"
appVersion: "24.5.0-rc.0"
kubeVersion: ">= 1.19.0-0"

home: https://github.com/astarte-platform/astarte-kubernetes-operator
sources:
  - https://github.com/astarte-platform/astarte-kubernetes-operator
keywords:
  - astarte
  - operator
  - iot
  - dataorchestration
maintainers:
  - name: drf
    email: dario.freddi@ispirata.com
  - name: matt-mazzucato
    email: mattia.mazzucato@secomind.com
  - name: annopaolo
    email: arnaldo.cesco@secomind.com
icon: https://github.com/astarte-platform/astarte-kubernetes-operator/blob/master/mascotte.svg
