vernemq_version: "{{ vars | json_query('vernemq.version') | default(astarte_tag, true) }}"
vernemq_k8s_enable_antiaffinity: "{{ false if (vars | json_query('vernemq.anti_affinity')) is sameas false else true }}"

vernemq_k8s_replicas: "{{ vars | json_query('vernemq.replicas') | default('1', true) }}"
k8s_image_pull_secrets:

vernemq_k8s_resources_requests_cpu: "{{ vars | json_query('vernemq.resources.requests.cpu') | default('200m', true) }}"
vernemq_k8s_resources_requests_memory: "{{ vars | json_query('vernemq.resources.requests.memory') | default('512M', true) }}"
vernemq_k8s_resources_limits_cpu: "{{ vars | json_query('vernemq.resources.limits.cpu') | default('800m', true) }}"
vernemq_k8s_resources_limits_memory: "{{ vars | json_query('vernemq.resources.limits.memory') | default('1024M', true) }}"

vernemq_k8s_volume_definition: "{{ vars | json_query('vernemq.storage.volume_definition') | default('', true) }}"
vernemq_k8s_storage_class_name: "{{ vars | json_query('vernemq.storage.class_name') | default(k8s_storage_class_name, true) }}"
vernemq_k8s_volume_size: "{{ vars | json_query('vernemq.storage.size') | default('4Gi', true) }}"
